'use client';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { motion } from 'framer-motion';
import { MapPin, Star, IndianRupee, Calendar, Building2, UtensilsCrossed, ArrowLeft, Shield, Sun, Thermometer, Droplets, Wind, Sunrise, Navigation, Loader2 } from 'lucide-react';

export default function DestinationDetailPage(){
 const{slug}=useParams<{slug:string}>();
 const{data:dest,isLoading,error}=useQuery({queryKey:['destination',slug],queryFn:()=>api.get(`/destinations/${slug}`),enabled:!!slug});

 if(isLoading)return(<div className="pt-24 pb-16 bg-ivory min-h-screen"><div className="max-w-7xl mx-auto px-4"><div className="animate-pulse"><div className="skeleton h-96 rounded-3xl mb-8"/><div className="skeleton h-8 w-64 mb-4"/></div></div></div>);
 if(error||!dest)return(<div className="pt-24 pb-16 bg-ivory min-h-screen flex items-center justify-center"><div className="text-center"><MapPin className="w-16 h-16 text-charcoal/20 mx-auto mb-4"/><h2 className="text-2xl font-bold">Destination not found</h2><Link href="/destinations" className="text-saffron">← Back</Link></div></div>);

 return(<div className="pt-20 pb-16 bg-ivory min-h-screen">
  <div className="relative h-[60vh] min-h-[400px] overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${dest.imageUrl||'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200'})`}}/><div className="absolute inset-0 bg-gradient-to-t from-navy/90 via-navy/30 to-transparent"/><div className="absolute top-6 left-6"><Link href="/destinations" className="glass px-4 py-2 rounded-xl text-sm font-medium text-white flex items-center gap-2"><ArrowLeft className="w-4 h-4"/>Back</Link></div><div className="absolute bottom-0 left-0 right-0 p-8 md:p-12"><div className="max-w-7xl mx-auto"><div className="flex items-center gap-3 mb-3"><span className="px-3 py-1 rounded-full bg-white/20 text-white text-xs">{dest.type}</span>{dest.isTrending&&<span className="px-3 py-1 rounded-full bg-saffron/80 text-white text-xs">Trending</span>}{dest.isHiddenGem&&<span className="px-3 py-1 rounded-full bg-emerald/80 text-white text-xs flex items-center gap-1"><Shield className="w-3 h-3"/>Hidden Gem</span>}</div><h1 className="text-4xl md:text-6xl font-bold text-white mb-2">{dest.name}</h1><div className="flex flex-wrap items-center gap-4 text-white/80 text-sm"><span><MapPin className="w-4 h-4 inline"/>{dest.stateId?.name||dest.state?.name}, India</span><span><Star className="w-4 h-4 inline fill-saffron text-saffron"/>{dest.rating} ({dest._count?.reviews||0})</span><span><IndianRupee className="w-4 h-4 inline"/>{dest.budget}</span><span><Calendar className="w-4 h-4 inline"/>{dest.bestSeason}</span></div></div></div></div>
  <div className="max-w-7xl mx-auto px-4 -mt-8 relative z-10"><div className="grid lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-8">
    <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="neumorphic-card p-8"><h2 className="text-2xl font-bold text-navy mb-4">About {dest.name}</h2><p className="text-charcoal/70 leading-relaxed">{dest.longDescription||dest.description}</p>{dest.tags&&<div className="flex flex-wrap gap-2 mt-6">{dest.tags.map((t:string)=><span key={t} className="px-3 py-1.5 rounded-full bg-saffron/5 text-saffron text-sm font-medium">#{t}</span>)}</div>}</motion.div>
    {dest.attractions?.length>0&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}}><h2 className="text-2xl font-bold text-navy mb-6">Top Attractions</h2><div className="grid sm:grid-cols-2 gap-4">{dest.attractions.map((a:any)=><div key={a.id} className="neumorphic-card p-4 flex gap-4"><div className="w-20 h-20 rounded-xl bg-cover bg-center" style={{backgroundImage:`url(${a.imageUrl||''})`}}/><div><h4 className="font-semibold">{a.name}</h4><p className="text-xs text-charcoal/50 mt-1 line-clamp-2">{a.description}</p>{a.entryFee&&<p className="text-xs text-emerald mt-1">₹{a.entryFee}</p>}</div></div>)}</div></motion.div>}
    {dest.hotels?.length>0&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.2}}><h2 className="text-2xl font-bold text-navy mb-6">Where to Stay</h2><div className="grid sm:grid-cols-2 gap-4">{dest.hotels.map((h:any)=><div key={h.id} className="neumorphic-card p-4"><h4 className="font-semibold">{h.name}</h4><div className="flex items-center gap-2 mt-1"><Star className="w-3.5 h-3.5 fill-saffron text-saffron"/><span className="text-sm">{h.rating}</span>{h.pricePerNight&&<span className="text-sm text-emerald ml-auto">₹{h.pricePerNight}/night</span>}</div>{h.amenities&&<div className="flex flex-wrap gap-1 mt-2">{h.amenities.slice(0,3).map((a:string)=><span key={a} className="px-2 py-0.5 rounded-full bg-softgray text-xs">{a}</span>)}</div>}</div>)}</div></motion.div>}
    {dest.restaurants?.length>0&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.3}}><h2 className="text-2xl font-bold text-navy mb-6">Where to Eat</h2><div className="grid sm:grid-cols-2 gap-4">{dest.restaurants.map((r:any)=><div key={r.id} className="neumorphic-card p-4"><div className="flex items-start justify-between"><div><h4 className="font-semibold">{r.name}</h4><p className="text-xs text-charcoal/50">{r.cuisine||'Multi-cuisine'}</p></div><span className="text-sm">{r.priceRange||'₹₹'}</span></div><div className="flex items-center gap-2 mt-2"><Star className="w-3.5 h-3.5 fill-saffron text-saffron"/><span className="text-sm">{r.rating}</span>{r.isVeg&&<span className="px-2 py-0.5 rounded-full bg-emerald/10 text-emerald text-xs">Veg</span>}</div></div>)}</div></motion.div>}
  </div><div className="space-y-6">
    <motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className="neumorphic-card p-6"><h3 className="font-semibold mb-4">Quick Info</h3><div className="space-y-3"><div className="flex items-center gap-3 text-sm"><IndianRupee className="w-4 h-4 text-saffron"/><span><strong>{dest.budget}</strong> starting</span></div><div className="flex items-center gap-3 text-sm"><Calendar className="w-4 h-4 text-saffron"/><span>Best: <strong>{dest.bestSeason}</strong></span></div><div className="flex items-center gap-3 text-sm"><Building2 className="w-4 h-4 text-saffron"/><span><strong>{dest._count?.hotels||0}</strong> hotels</span></div><div className="flex items-center gap-3 text-sm"><UtensilsCrossed className="w-4 h-4 text-saffron"/><span><strong>{dest._count?.restaurants||0}</strong> restaurants</span></div></div><Link href={`/planner?destination=${dest.name}`} className="btn-primary w-full mt-6 flex items-center justify-center gap-2"><Navigation className="w-5 h-5"/>Plan My Trip</Link></motion.div>
    <motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{delay:.1}} className="neumorphic-card p-6"><h3 className="font-semibold mb-4">Weather</h3><div className="flex items-center gap-4 mb-4"><Sun className="w-10 h-10 text-saffron"/><div><div className="text-3xl font-bold">28°C</div><div className="text-sm text-charcoal/50">Partly cloudy</div></div></div><div className="grid grid-cols-2 gap-2 text-xs"><span><Thermometer className="w-3.5 h-3.5 inline"/>30°</span><span><Droplets className="w-3.5 h-3.5 inline"/>45%</span><span><Wind className="w-3.5 h-3.5 inline"/>12km/h</span><span><Sunrise className="w-3.5 h-3.5 inline"/>6:15AM</span></div></motion.div>
  </div></div></div></div>);
}
