'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { cn } from '@/lib/utils';
import { Search, MapPin, ArrowRight, Sparkles, Compass, Star, Heart, Mountain, Waves, Castle, Church, Leaf, Camera, Route, Plane, ChevronRight, Shield, Users } from 'lucide-react';

function Counter({ end, label, duration = 2 }: { end: number; label: string; duration?: number }) {
  const [count, setCount] = useState(0);
  useEffect(() => { let startTime: number; let raf: number; const animate = (timestamp: number) => { if (!startTime) startTime = timestamp; const progress = Math.min((timestamp - startTime) / (duration * 1000), 1); setCount(Math.floor(progress * end)); if (progress < 1) raf = requestAnimationFrame(animate); }; raf = requestAnimationFrame(animate); return () => cancelAnimationFrame(raf); }, [end, duration]);
  return (<div className="text-center"><div className="text-3xl lg:text-4xl font-bold text-saffron">{count.toLocaleString()}+</div><div className="text-sm text-white/50 mt-1">{label}</div></div>);
}

function DestinationCard({ dest }: { dest: any }) {
  return (<Link href={`/destinations/${dest.slug}`}><motion.div whileHover={{ y: -4 }} className="group relative overflow-hidden rounded-2xl neumorphic-card cursor-pointer h-[320px]"><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent z-10"/><div className="absolute inset-0 bg-cover bg-center group-hover:scale-105 transition-transform duration-700" style={{ backgroundImage: `url(${dest.imageUrl || 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600'})` }}/><div className="absolute bottom-0 left-0 right-0 z-20 p-5"><div className="flex items-center gap-2 mb-1"><span className="px-2 py-0.5 rounded-full bg-white/20 backdrop-blur-sm text-white text-xs">{dest.stateId?.name || 'India'}</span><span className="flex items-center gap-1 text-white/90 text-xs"><Star className="w-3 h-3 fill-saffron text-saffron"/>{dest.rating}</span></div><h3 className="text-xl font-bold text-white mb-1">{dest.name}</h3><div className="flex items-center gap-3 text-white/80 text-sm"><span>From {dest.budget}</span><span className="w-1 h-1 rounded-full bg-white/50"/><span>{dest.bestSeason}</span></div></div></motion.div></Link>);
}

const experiences = [{icon:Mountain,label:'Mountains',href:'/destinations?type=Hill%20Station',color:'bg-blue-50 text-blue-600'},{icon:Waves,label:'Beaches',href:'/destinations?type=Beach',color:'bg-cyan-50 text-cyan-600'},{icon:Castle,label:'Heritage',href:'/destinations?type=Heritage',color:'bg-amber-50 text-amber-600'},{icon:Church,label:'Spiritual',href:'/destinations?type=Spiritual',color:'bg-purple-50 text-purple-600'},{icon:Leaf,label:'Nature',href:'/destinations?type=Nature',color:'bg-emerald-50 text-emerald-600'},{icon:Camera,label:'Photography',href:'/destinations',color:'bg-pink-50 text-pink-600'},{icon:Route,label:'Road Trips',href:'/destinations?type=Adventure',color:'bg-orange-50 text-orange-600'},{icon:Plane,label:'Adventure',href:'/destinations?type=Adventure',color:'bg-red-50 text-red-600'}];

export default function HomePage() {
  const [searchQuery, setSearchQuery] = useState('');
  const { data: trendingData } = useQuery({ queryKey: ['trending-destinations'], queryFn: () => api.get<any[]>('/destinations/trending') });
  const { data: hiddenData } = useQuery({ queryKey: ['hidden-gems'], queryFn: () => api.get<any[]>('/destinations/hidden-gems') });
  const trending = trendingData || [];
  const hiddenGems = hiddenData || [{ name:'Tirthan Valley',slug:'tirthan-valley',description:'Pristine valley with trout fishing.'},{ name:'Varkala',slug:'varkala',description:'Stunning cliffside beach with red laterite cliffs.'},{ name:'Orchha',slug:'orchha',description:'Forgotten kingdom with magnificent cenotaphs.'}];

  return (<div>
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden"><div className="absolute inset-0"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:'url(https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920)'}}/><div className="absolute inset-0 bg-gradient-to-b from-navy/70 via-navy/50 to-navy/80"/></div><div className="relative z-10 max-w-7xl mx-auto px-4 py-32 text-center"><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border-white/20 text-white/90 text-sm mb-8"><Sparkles className="w-4 h-4 text-saffron"/>AI-Powered Indian Travel Platform</div><h1 className="text-5xl md:text-7xl lg:text-8xl font-display font-bold text-white mb-6">Your Journey.<br/><span className="text-saffron">Your Way.</span></h1><p className="text-xl md:text-2xl text-white/70 max-w-2xl mx-auto mb-12">Discover India, plan smarter, and turn every trip into a story.</p></motion.div><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.2}} className="glass rounded-3xl p-6 max-w-4xl mx-auto shadow-2xl"><div className="flex flex-col md:flex-row gap-3 mb-3"><div className="flex-1 relative"><MapPin className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-saffron"/><input type="text" placeholder="Where do you want to go?" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} className="w-full pl-12 pr-4 py-4 rounded-2xl border border-softgray bg-white/90 text-navy placeholder:text-charcoal/40 focus:outline-none focus:ring-2 focus:ring-saffron/50 text-lg" onKeyDown={e=>{if(e.key==='Enter'&&searchQuery)window.location.href=`/planner?destination=${encodeURIComponent(searchQuery)}`;}}/></div><Link href={searchQuery?`/planner?destination=${encodeURIComponent(searchQuery)}`:'/planner'} className="btn-primary flex items-center gap-2 text-lg py-4 px-8">Plan My Trip <ArrowRight className="w-5 h-5"/></Link></div></motion.div><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{duration:1,delay:.5}} className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-8 max-w-3xl mx-auto"><Counter end={40} label="Destinations"/><Counter end={36} label="States"/><Counter end={50} label="Demo Trips" duration={1.5}/><Counter end={100} label="AI-Powered" duration={1}/></motion.div></div><motion.div animate={{y:[0,8,0]}} transition={{duration:2,repeat:Infinity}} className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white/50"><ChevronRight className="w-6 h-6 rotate-90"/></motion.div></section>

    <section className="py-24 bg-ivory"><div className="max-w-7xl mx-auto px-4"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="text-center mb-16"><h2 className="text-4xl md:text-5xl font-display font-bold text-navy mb-4">India, waiting to be discovered.</h2><p className="text-lg text-charcoal/60 max-w-2xl mx-auto">From snow-capped peaks to sun-kissed beaches, every corner of India tells a story.</p></motion.div>{trending.length>0?<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{trending.slice(0,6).map((d:any,i:number)=><motion.div key={d.id||i} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><DestinationCard dest={d}/></motion.div>)}</div>:<div className="grid grid-cols-3 gap-6">{Array.from({length:6}).map((_,i)=><div key={i} className="neumorphic-card h-80 skeleton"/>)}</div>}<div className="text-center mt-12"><Link href="/destinations" className="btn-outline inline-flex items-center gap-2">Explore All Destinations <ArrowRight className="w-4 h-4"/></Link></div></div></section>

    <section className="py-24 bg-white"><div className="max-w-7xl mx-auto px-4"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="text-center mb-16"><h2 className="text-4xl font-bold text-navy mb-4">Travel your way.</h2></motion.div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">{experiences.map((exp,i)=><motion.div key={exp.label} initial={{opacity:0,scale:.9}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:i*.05}}><Link href={exp.href} className="neumorphic-card p-6 flex flex-col items-center gap-3 cursor-pointer group hover:-translate-y-1 transition-all block"><div className={cn('w-14 h-14 rounded-2xl flex items-center justify-center',exp.color)}><exp.icon className="w-6 h-6"/></div><span className="font-semibold text-sm">{exp.label}</span></Link></motion.div>)}</div></div></section>

    <section className="py-24 bg-navy text-white"><div className="max-w-7xl mx-auto px-4"><div className="grid lg:grid-cols-2 gap-16 items-center"><motion.div initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 text-saffron text-sm mb-6"><Sparkles className="w-4 h-4"/>AI Trip Planner</div><h2 className="text-4xl md:text-5xl font-bold mb-6">Your personal AI<br/><span className="text-saffron">travel companion.</span></h2><p className="text-lg text-white/60 mb-8">Tell us your preferences and our AI creates a personalized itinerary in seconds.</p><div className="space-y-3">{[{step:1,q:'Where do you want to go?'},{step:2,q:'How long are you staying?'},{step:3,q:'What\'s your travel style?'},{step:4,q:'What\'s your budget?'},{step:5,q:'Your itinerary is ready! 🎉'}].map((s,i)=><div key={s.step} className={cn('flex items-center gap-4 p-4 rounded-xl',i===0?'bg-saffron/10 border border-saffron/30':'')}><div className={cn('w-8 h-8 rounded-lg flex items-center justify-center text-sm font-bold',i===0?'bg-saffron text-white':'bg-white/10')}>{s.step}</div><span>{s.q}</span></div>)}</div><Link href="/planner" className="btn-primary inline-flex items-center gap-2 mt-8"><Sparkles className="w-5 h-5"/>Build My Journey</Link></motion.div><motion.div initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="glass rounded-3xl p-8 border-white/10"><div className="flex justify-between mb-6"><div><h3 className="text-xl font-bold">Rajasthan Heritage</h3><p className="text-white/60 text-sm">7 Days · ₹21,500</p></div><Heart className="w-5 h-5 text-saffron"/></div><div className="space-y-4">{[{day:'Day 1',title:'Arrival in Jaipur',desc:'City Palace, Hawa Mahal, Bapu Bazaar',icon:'🏰'},{day:'Day 2',title:'Amer & Jaipur',desc:'Amer Fort, Nahargarh sunset',icon:'🐘'},{day:'Day 3',title:'Pushkar Journey',desc:'Brahma Temple, Pushkar Lake',icon:'🐪'},{day:'Day 4',title:'Jodhpur Blue City',desc:'Mehrangarh Fort, old city',icon:'💙'},{day:'Day 5',title:'Udaipur Romance',desc:'Lake Pichola, rooftop dinner',icon:'🌅'}].map((d,i)=><div key={i} className="flex gap-4 p-3 rounded-xl bg-white/5"><div className="w-10 h-10 rounded-xl bg-saffron/20 flex items-center justify-center text-lg">{d.icon}</div><div><div className="text-saffron text-xs">{d.day}</div><div className="font-semibold text-sm">{d.title}</div><div className="text-white/50 text-xs">{d.desc}</div></div></div>)}</div></motion.div></div></div></section>

    <section className="py-24 bg-ivory"><div className="max-w-7xl mx-auto px-4"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="text-center mb-16"><h2 className="text-4xl font-bold text-navy mb-4">Not every beautiful place is crowded.</h2></motion.div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{hiddenGems.slice(0,6).map((g:any,i:number)=><motion.div key={g.slug||i} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><Link href={`/destinations/${g.slug}`}><div className="neumorphic-card p-6 hover:-translate-y-1 transition-all group"><div className="flex items-center gap-2 mb-3"><div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center"><Shield className="w-4 h-4 text-emerald"/></div><span className="text-xs text-emerald uppercase tracking-wide">Hidden Gem</span></div><h3 className="text-lg font-bold group-hover:text-saffron transition-colors">{g.name}</h3><p className="text-sm text-charcoal/70 mt-2">{g.description}</p><div className="mt-4 flex items-center gap-1 text-saffron text-sm font-semibold">Explore <ArrowRight className="w-3 h-3"/></div></div></Link></motion.div>)}</div></div></section>

    <section className="py-24 bg-navy"><div className="max-w-4xl mx-auto px-4 text-center"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 text-saffron text-sm mb-6"><Compass className="w-4 h-4"/>Start Your Journey Today</div><h2 className="text-4xl md:text-6xl font-bold text-white mb-6">Where will you<br/><span className="text-saffron">wander next?</span></h2><p className="text-xl text-white/60 mb-10 max-w-2xl mx-auto">Join thousands of travelers who use MusafirX to discover, plan, and experience the best of India.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/planner" className="btn-primary text-lg px-10 py-4 inline-flex items-center gap-2"><Sparkles className="w-5 h-5"/>Build My Journey</Link><Link href="/explore" className="btn-outline text-lg px-10 py-4 inline-flex items-center gap-2 border-white/30 text-white hover:bg-white/10"><Compass className="w-5 h-5"/>Explore India</Link></div></motion.div></div></section>
  </div>);
}
