'use client';
import { useState } from 'react';
import { api } from '@/lib/api';
import { Check, Plus, Trash2, Loader2, Sparkles, Backpack } from 'lucide-react';
import toast from 'react-hot-toast';

const di=['Light jacket','Power bank','Trekking shoes','Sunscreen SPF 50+','Water bottle','Basic medicines','Camera/Phone charger','Passport/ID proofs','Sunglasses','Lip balm'];
export default function PackingPage(){
 const[f,sf]=useState({destination:'',duration:'5',weather:'moderate',activities:''});
 const[items,si]=useState(di.map((item,i)=>({id:String(i),item,checked:false})));
 const[g,sg]=useState(false);const[n,sn]=useState('');
 const gen=async()=>{if(!f.destination){toast.error('Enter destination first');return;}sg(true);try{await api.post('/ai/packing-list',{destination:f.destination,duration:parseInt(f.duration),weather:f.weather,activities:f.activities.split(',').map(s=>s.trim()).filter(Boolean)});toast.success('List updated!');}catch{}finally{sg(false);}};
 const toggle=(id:string)=>si(prev=>prev.map(i=>i.id===id?{...i,checked:!i.checked}:i));
 const add=()=>{if(!n.trim())return;si(prev=>[...prev,{id:Date.now().toString(),item:n.trim(),checked:false}]);sn('');};
 const remove=(id:string)=>si(prev=>prev.filter(i=>i.id!==id));
 const cc=items.filter(i=>i.checked).length;const progress=items.length?(cc/items.length)*100:0;
 return(<div className="pt-24 pb-16 bg-ivory min-h-screen"><div className="max-w-3xl mx-auto px-4"><div className="text-center mb-10"><Backpack className="w-12 h-12 text-saffron mx-auto mb-3"/><h1 className="text-3xl font-bold text-navy">Packing Assistant</h1></div><div className="neumorphic-card p-6 mb-8"><div className="grid sm:grid-cols-2 gap-4 mb-4"><div><label className="text-sm font-semibold">Destination</label><input value={f.destination} onChange={e=>sf({...f,destination:e.target.value})} placeholder="e.g. Ladakh" className="input-field text-sm"/></div><div><label className="text-sm font-semibold">Duration</label><input type="number" value={f.duration} onChange={e=>sf({...f,duration:e.target.value})} className="input-field text-sm"/></div><div><label className="text-sm font-semibold">Weather</label><select value={f.weather} onChange={e=>sf({...f,weather:e.target.value})} className="input-field text-sm"><option value="cold">❄ Cold</option><option value="moderate">☀ Moderate</option><option value="hot">🔥 Hot</option><option value="rainy">🌧 Rainy</option></select></div><div><label className="text-sm font-semibold">Activities</label><input value={f.activities} onChange={e=>sf({...f,activities:e.target.value})} placeholder="trekking, swimming" className="input-field text-sm"/></div></div><button onClick={gen} disabled={g} className="btn-primary w-full flex items-center justify-center gap-2">{g?<Loader2 className="w-5 h-5 animate-spin"/>:<Sparkles className="w-5 h-5"/>}{g?'Generating...':'Generate Packing List'}</button></div><div className="mb-6"><div className="flex justify-between mb-2"><span className="text-sm font-semibold">{cc} of {items.length} packed</span><span className="text-sm text-charcoal/50">{Math.round(progress)}%</span></div><div className="w-full bg-softgray rounded-full h-2.5"><div className="h-full rounded-full bg-emerald" style={{width:`${progress}%`}}/></div></div><div className="neumorphic-card p-6"><div className="space-y-2 mb-4">{items.map(item=><div key={item.id} className={`flex items-center gap-3 p-3 rounded-xl ${item.checked?'bg-emerald/5':'bg-ivory'}`}><button onClick={()=>toggle(item.id)} className={`w-6 h-6 rounded-lg border-2 flex items-center justify-center ${item.checked?'bg-emerald border-emerald text-white':'border-softgray hover:border-saffron'}`}>{item.checked&&<Check className="w-3.5 h-3.5"/>}</button><span className={`flex-1 text-sm ${item.checked?'line-through text-charcoal/40':'text-charcoal'}`}>{item.item}</span><button onClick={()=>remove(item.id)} className="p-1 rounded-lg hover:bg-red-50"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div><form onSubmit={e=>{e.preventDefault();add();}} className="flex gap-2"><input value={n} onChange={e=>sn(e.target.value)} placeholder="Add item..." className="input-field text-sm flex-1"/><button type="submit" className="btn-primary p-2.5 rounded-xl"><Plus className="w-5 h-5"/></button></form></div></div></div>);
}
