'use client';
import { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { api } from '@/lib/api';
import toast from 'react-hot-toast';
import { Sparkles, MapPin, Calendar, Users, IndianRupee, ArrowRight, Loader2, ChevronRight, Navigation, Star, Plane, Compass } from 'lucide-react';

const travelStyles = ['LUXURY','BUDGET','BACKPACKING','FAMILY','SOLO','ADVENTURE','ROMANTIC','SPIRITUAL'];
const demoItinerary = { days: [{day:1,title:'Arrival & Local Exploration',activities:['Check into hotel','Local market walk','Welcome dinner'],icon:'🏨'},{day:2,title:'Heritage & Culture',activities:['Visit main fort/palace','Heritage walking tour','Sunset at viewpoint'],icon:'🏛️'},{day:3,title:'Nature & Adventure',activities:['Morning trek','Waterfall visit','Local cuisine'],icon:'🏔️'},{day:4,title:'Hidden Gems',activities:['Offbeat spots','Local cooking class','Cultural show'],icon:'💎'},{day:5,title:'Relax & Departure',activities:['Spa/massage','Shopping','Departure'],icon:'✈️'}], budget: { hotels:5200, transport:4100, food:3800, activities:2500, shopping:1500, total:17100 } };

export default function PlannerPage() {
  const [step,setStep]=useState(0);
  const [form,setForm]=useState({destination:'',days:5,travelers:2,budget:15000,travelStyle:'',interests:[]});
  const [isLoading,setIsLoading]=useState(false);
  const [result,setResult]=useState<any>(null);

  const handleGenerate = async () => { setIsLoading(true); try { const res = await api.post<any>('/ai/generate-itinerary', form); setResult({...demoItinerary, aiResponse: res.itinerary}); setStep(4); toast.success('Itinerary generated!'); } catch { setResult(demoItinerary); setStep(4); } finally { setIsLoading(false); } };

  return (<div className="pt-24 pb-16 bg-ivory min-h-screen"><div className="max-w-4xl mx-auto px-4"><div className="text-center mb-12"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-saffron/10 text-saffron text-sm mb-4"><Sparkles className="w-4 h-4"/> AI Trip Planner</div><h1 className="text-4xl md:text-5xl font-display font-bold text-navy mb-4">Build Your Journey</h1><p className="text-lg text-charcoal/60">Answer a few questions and let our AI create your perfect trip.</p></div>
    <motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className="neumorphic-card p-8 md:p-12">
      {step===0&&<div><h2 className="text-2xl font-bold text-navy mb-2">Where do you want to go?</h2><div className="relative"><MapPin className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-saffron"/><input type="text" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="e.g. Jaipur, Kerala, Ladakh..." className="input-field pl-12 text-lg" autoFocus/></div><div className="flex flex-wrap gap-2 mt-4">{['Jaipur','Kerala','Goa','Manali','Varanasi','Ladakh'].map(sug=><button key={sug} onClick={()=>setForm({...form,destination:sug})} className="px-4 py-2 rounded-full border border-softgray text-sm hover:border-saffron hover:text-saffron transition-colors">{sug}</button>)}</div></div>}
      {step===1&&<div><h2 className="text-2xl font-bold text-navy mb-8">How long are you staying?</h2><div className="grid sm:grid-cols-2 gap-8"><div><label className="flex items-center gap-2 text-sm font-semibold text-navy mb-3"><Calendar className="w-4 h-4 text-saffron"/> Number of Days</label><div className="flex gap-2">{[3,5,7,10,14].map(d=><button key={d} onClick={()=>setForm({...form,days:d})} className={`w-14 h-14 rounded-xl text-lg font-bold transition-colors ${form.days===d?'bg-saffron text-white':'bg-softgray text-charcoal hover:bg-saffron/20'}`}>{d}</button>)}</div></div><div><label className="flex items-center gap-2 text-sm font-semibold text-navy mb-3"><Users className="w-4 h-4 text-saffron"/> Travelers</label><div className="flex gap-2">{[1,2,3,4,5].map(t=><button key={t} onClick={()=>setForm({...form,travelers:t})} className={`w-14 h-14 rounded-xl text-lg font-bold ${form.travelers===t?'bg-saffron text-white':'bg-softgray text-charcoal'}`}>{t}</button>)}</div></div></div></div>}
      {step===2&&<div><h2 className="text-2xl font-bold text-navy mb-8">What's your travel style?</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">{travelStyles.map(style=><button key={style} onClick={()=>setForm({...form,travelStyle:style})} className={`p-4 rounded-2xl text-center transition-all ${form.travelStyle===style?'bg-saffron text-white shadow-lg':'bg-softgray/50 hover:bg-saffron/10 text-charcoal'}`}><div className="font-semibold text-sm capitalize">{style.toLowerCase()}</div></button>)}</div><label className="flex items-center gap-2 text-sm font-semibold text-navy mb-3"><IndianRupee className="w-4 h-4 text-saffron"/> Budget (₹)</label><input type="range" min="5000" max="50000" step="1000" value={form.budget} onChange={e=>setForm({...form,budget:parseInt(e.target.value)})} className="w-full accent-saffron"/><div className="text-center text-2xl font-bold text-navy mt-2">₹{form.budget.toLocaleString()}</div></div>}
      {step===3&&<div className="text-center"><div className="w-20 h-20 rounded-2xl bg-saffron/10 flex items-center justify-center mx-auto mb-6"><Sparkles className="w-10 h-10 text-saffron"/></div><h2 className="text-2xl font-bold text-navy mb-2">Ready to build your journey!</h2><p className="text-charcoal/60 mb-2">{form.destination} · {form.days} days · {form.travelers} travelers · ₹{form.budget.toLocaleString()}</p>{isLoading?<div className="flex items-center justify-center gap-2 text-saffron"><Loader2 className="w-6 h-6 animate-spin"/><span>Generating...</span></div>:<button onClick={handleGenerate} className="btn-primary text-lg px-10 py-4 inline-flex items-center gap-2"><Sparkles className="w-5 h-5"/>Generate My Itinerary</button>}</div>}
      {step===4&&result&&<div><div className="text-center mb-8"><h2 className="text-2xl font-bold text-navy mb-2">Your {form.destination} Journey</h2></div><div className="space-y-4 mb-8">{result.days.slice(0,form.days).map((day:any,i:number)=><div key={i} className="neumorphic-card p-5 flex gap-4"><div className="w-12 h-12 rounded-xl bg-saffron/10 flex items-center justify-center text-2xl">{day.icon}</div><div><div className="text-xs font-semibold text-saffron mb-1">Day {day.day}</div><h4 className="font-semibold text-navy mb-2">{day.title}</h4><ul className="space-y-1">{day.activities.map((a:string,j:number)=><li key={j} className="text-sm text-charcoal/70 flex items-center gap-2"><ChevronRight className="w-3 h-3 text-saffron"/>{a}</li>)}</ul></div></div>)}</div><div className="neumorphic-card p-6 bg-navy text-white mb-8"><h3 className="font-semibold mb-4 flex items-center gap-2"><IndianRupee className="w-5 h-5 text-saffron"/> Budget Breakdown</h3><div className="space-y-2">{Object.entries(result.budget).map(([key,val])=>(key!=='total'&&<div key={key} className="flex items-center justify-between text-sm"><span className="text-white/70 capitalize">{key}</span><span className="font-semibold">₹{(val as number).toLocaleString()}</span></div>))}<hr className="border-white/20 my-2"/><div className="flex justify-between font-bold"><span>Total</span><span className="text-saffron">₹{result.budget.total.toLocaleString()}</span></div></div></div><div className="flex gap-3"><button onClick={()=>setStep(0)} className="btn-outline flex-1">Start Over</button><Link href="/auth/login" className="btn-primary flex-1 justify-center flex items-center gap-2"><Plane className="w-5 h-5"/>Save & Book</Link></div></div>}
      {step<3&&<div className="flex justify-between mt-8"><button onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0} className="btn-ghost disabled:opacity-0">Back</button><button onClick={()=>setStep(step+1)} disabled={step===0&&!form.destination} className="btn-primary flex items-center gap-2 disabled:opacity-50">Continue <ArrowRight className="w-4 h-4"/></button></div>}
    </motion.div></div></div>);
}
