'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useAuthStore } from '@/store/auth';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { formatCurrency } from '@/lib/utils';
import { motion } from 'framer-motion';
import { LayoutDashboard, Heart, Plane, PlusCircle, MapPin, Calendar, IndianRupee, Users, Star, Compass, Sparkles, Loader2, LogIn } from 'lucide-react';

export default function DashboardPage() {
  const { user, isAuthenticated, isLoading: authLoading } = useAuthStore();
  const [activeTab, setActiveTab] = useState('overview');
  const { data: trips } = useQuery({ queryKey: ['my-trips'], queryFn: () => api.get<any>('/trips'), enabled: isAuthenticated });
  const { data: saved } = useQuery({ queryKey: ['saved'], queryFn: () => api.get<any>('/saved'), enabled: isAuthenticated });

  if (authLoading) return <div className="pt-24 flex justify-center"><Loader2 className="w-8 h-8 animate-spin text-saffron"/></div>;
  if (!isAuthenticated) return <div className="pt-24 pb-16 bg-ivory min-h-screen flex items-center justify-center"><div className="text-center"><Plane className="w-16 h-16 text-charcoal/20 mx-auto mb-4"/><h2 className="text-2xl font-bold text-navy mb-2">Sign in to view your dashboard</h2><Link href="/auth/login" className="btn-primary inline-flex items-center gap-2"><LogIn className="w-5 h-5"/> Sign In</Link></div></div>;

  const totalSpent = trips?.reduce((sum: number, t: any) => sum + (t.spentSoFar || 0), 0) || 0;
  const tabs = [{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'trips',label:'My Trips',icon:Plane},{id:'saved',label:'Saved Places',icon:Heart}];

  return (<div className="pt-24 pb-16 bg-ivory min-h-screen"><div className="max-w-7xl mx-auto px-4"><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10"><div><h1 className="text-3xl md:text-4xl font-display font-bold text-navy">Welcome back, {user?.name?.split(' ')[0]} 👋</h1></div><Link href="/planner" className="btn-primary inline-flex items-center gap-2"><PlusCircle className="w-5 h-5"/> Create Trip</Link></motion.div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{icon:Plane,label:'Total Trips',value:trips?.length||0,color:'text-saffron'},{icon:MapPin,label:'Saved',value:saved?.length||0,color:'text-navy'},{icon:IndianRupee,label:'Total Spent',value:formatCurrency(totalSpent),color:'text-emerald'},{icon:Star,label:'Reviews',value:'12',color:'text-amber-500'}].map((stat,i)=>(<motion.div key={i} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*0.1}} className="neumorphic-card p-5 text-center"><stat.icon className={`w-6 h-6 ${stat.color} mx-auto mb-2`}/><div className="text-2xl font-bold text-navy">{stat.value}</div><div className="text-xs text-charcoal/50 mt-1">{stat.label}</div></motion.div>))}</div>
    <div className="flex gap-2 mb-8 border-b border-softgray">{tabs.map(tab=><button key={tab.id} onClick={()=>setActiveTab(tab.id)} className={`flex items-center gap-2 px-4 py-3 text-sm font-medium rounded-t-xl transition-colors ${activeTab===tab.id?'text-saffron border-b-2 border-saffron bg-saffron/5':'text-charcoal/50 hover:text-charcoal'}`}><tab.icon className="w-4 h-4"/>{tab.label}</button>)}</div>
    {activeTab==='overview'&&<div className="space-y-8">{trips&&trips.length>0&&<div><h2 className="text-xl font-bold text-navy mb-4">Upcoming & Recent</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{trips.slice(0,3).map((trip:any,i:number)=><Link key={trip.id} href={`/trips/${trip.id}`}><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*0.1}} className="neumorphic-card p-5 hover:-translate-y-1 transition-all group"><div className="flex items-start justify-between mb-3"><div><h3 className="font-semibold text-navy group-hover:text-saffron transition-colors">{trip.title}</h3><p className="text-xs text-charcoal/50">{trip.destinationId?.name}</p></div><span className={`px-2 py-1 rounded-full text-xs font-medium ${trip.status==='PLANNED'?'bg-blue-50 text-blue-600':trip.status==='ACTIVE'?'bg-emerald-50 text-emerald':'bg-softgray text-charcoal/60'}`}>{trip.status}</span></div><div className="flex items-center gap-4 text-xs text-charcoal/50">{trip.totalDays&&<span><Calendar className="w-3 h-3 inline"/> {trip.totalDays}d</span>}{trip.budget&&<span><IndianRupee className="w-3 h-3 inline"/> {formatCurrency(trip.budget)}</span>}</div></motion.div></Link>)}</div></div>}<div className="neumorphic-card p-8 bg-gradient-to-br from-navy to-navy-600 text-white"><div className="flex items-center gap-2 mb-4"><Sparkles className="w-6 h-6 text-saffron"/><h2 className="text-xl font-bold">AI Recommendations</h2></div><div className="grid sm:grid-cols-3 gap-4">{['Rajasthan Heritage Trail','Kerala Backwaters','Meghalaya Explorer'].map(rec=><div key={rec} className="bg-white/10 rounded-xl p-4"><Compass className="w-5 h-5 text-saffron mb-2"/><p className="font-semibold text-sm">{rec}</p></div>)}</div></div></div>}
    {activeTab==='trips'&&(trips&&trips.length>0?<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{trips.map((trip:any)=><Link key={trip.id} href={`/trips/${trip.id}`}><div className="neumorphic-card p-5 hover:-translate-y-1 transition-all"><div className="flex items-start justify-between mb-3"><div><h3 className="font-semibold text-navy">{trip.title}</h3><p className="text-xs text-charcoal/50">{trip.destinationId?.name}</p></div><span className="px-2 py-1 rounded-full text-xs font-medium bg-blue-50 text-blue-600">{trip.status}</span></div></div></Link>)}</div>:<div className="text-center py-20"><Plane className="w-16 h-16 text-charcoal/20 mx-auto mb-4"/><h3 className="text-xl font-bold text-navy mb-2">No trips yet</h3><Link href="/planner" className="btn-primary inline-flex items-center gap-2 mt-4"><Sparkles className="w-5 h-5"/> Plan Your Trip</Link></div>)}
    {activeTab==='saved'&&(saved&&saved.length>0?<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{saved.map((s:any)=><Link key={s.id} href={`/destinations/${s.destinationId?.slug}`}><div className="neumorphic-card p-4 hover:-translate-y-1 transition-all flex items-center gap-4"><div className="w-16 h-16 rounded-xl bg-cover bg-center" style={{backgroundImage:`url(${s.destinationId?.imageUrl||''})`}}/><div><h4 className="font-semibold text-navy text-sm">{s.destinationId?.name}</h4><div className="flex items-center gap-1 mt-1"><Star className="w-3 h-3 fill-saffron text-saffron"/><span className="text-xs">{s.destinationId?.rating}</span></div></div></div></Link>)}</div>:<div className="text-center py-20"><Heart className="w-16 h-16 text-charcoal/20 mx-auto mb-4"/><h3 className="text-xl font-bold text-navy mb-2">No saved places</h3><Link href="/destinations" className="btn-outline inline-flex items-center gap-2 mt-4"><Compass className="w-5 h-5"/> Explore</Link></div>)}
  </div></div>);
}
